push

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -6,6 +6,10 @@ on:
     branches:
       - 'main'
 
+env:
+  GO_VERSION: 1.18
+  GOLANGCI_LINT_VERSION: v1.46.2
+
 # This workflow runs for not-yet-reviewed external contributions and so it
 # intentionally has no write access and only limited read access to the
 # repository.
@@ -14,23 +18,8 @@ permissions:
 
 jobs:
   lint:
-    name: "Run golangci-lint"
-    runs-on: ubuntu-latest
-    steps:
-      - name: "Fetch source code"
-        uses: actions/checkout@v2
-
-      - name: "Download golang-lint"
-        run: |
-          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v1.46.2
-          golangci-lint version
-      - name: "lint"
-        run: |
-          golangci-lint run -v
-
-  unit-tests:
-    name: "Unit Tests"
-    runs-on: ubuntu-latest
+    name: "lint"
+    runs-on: ubuntu-22.04
     steps:
       - name: "Fetch source code"
         uses: actions/checkout@v2
@@ -38,34 +27,7 @@ jobs:
       - name: Install Go toolchain
         uses: actions/setup-go@v2
         with:
-          go-version: 1.18
-
-      - name: "Unit tests"
-        run: |
-          go test ./...
-
-  consistency-checks:
-    name: "Code Consistency Checks"
-    runs-on: ubuntu-latest
-    steps:
-      - name: "Fetch source code"
-        uses: actions/checkout@v2
-
-      - name: Install Go toolchain
-        uses: actions/setup-go@v2
-        with:
-          go-version: 1.18
-
-      - name: "go.mod and go.sum consistency check"
-        run: |
-          go mod tidy
-          if [[ -n "$(git status --porcelain)" ]]; then
-            echo >&2 "ERROR: go.mod/go.sum are not up-to-date. Run 'go mod tidy' and then commit the updated files."
-            exit 1
-          fi
-      - name: "go vet"
-        run: |
-          go vet ./...
+          go-version: ${{env.GO_VERSION}}
 
       - name: "go fmt check"
         run: |
@@ -75,3 +37,56 @@ jobs:
             echo "$files"
             exit 1
           fi
+
+      - name: "go vet"
+        run: |
+          go vet ./...
+
+      - name: "go.mod and go.sum consistency check"
+        run: |
+          go mod tidy
+          if [[ -n "$(git status --porcelain)" ]]; then
+            echo >&2 "ERROR: go.mod/go.sum are not up-to-date. Run 'go mod tidy' and then commit the updated files."
+            exit 1
+          fi
+
+      - name: "Download golang-lint"
+        run: |
+          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin ${{ env.GOLANGCI_LINT_VERSION }}
+          golangci-lint version
+
+      - name: "lint"
+        run: |
+          golangci-lint run -v
+
+  unit-tests:
+    name: "Unit Tests"
+    runs-on: ubuntu-22.04
+    steps:
+      - name: "Fetch source code"
+        uses: actions/checkout@v2
+
+      - name: Install Go toolchain
+        uses: actions/setup-go@v2
+        with:
+          go-version: ${{env.GO_VERSION}}
+
+      - name: "Unit tests"
+        run: |
+          go test ./...
+
+  configuration_tests:
+    name: "Config File Tests"
+    runs-on: ubuntu-22.04
+      - name: "Fetch source code"
+        uses: actions/checkout@v2
+
+      - name: Install Go toolchain
+        uses: actions/setup-go@v2
+        with:
+          go-version: ${{env.GO_VERSION}}
+
+      - name: compile binary
+        run: |
+          make
+          devconsul help
